//! Paintable grid splat — per-cell scalar values rendered as a splat.
//!
//! `GridSplat` is an asset whose source of truth is a `(width × height)`
//! grid of `f32` cell values. The underlying `Splat` (one point per cell)
//! is regenerated by the [`sync_grid_to_splat`] system whenever the
//! `GridSplat` asset changes.
//!
//! The default cell-to-point mapping puts the grid in the local XZ plane,
//! lifts each point along Y by `value * height_scale`, and tints it by
//! sampling `colormap` at the cell value. Override `height_scale` /
//! `colormap` to repurpose the same machinery for masks (height_scale
//! 0, colormap mapping `[0..2]` to dark→bright), heightmaps (height_scale
//! large, no colormap), etc.

use bevy::asset::Asset;
use bevy::prelude::*;

use crate::splat::{Splat, Splat3d, SplatPoint};

/// Per-cell scalar grid that drives a `Splat`.
///
/// Mutate cells via [`Self::set`] / [`Self::set_many`] / [`Self::fill`];
/// the sync system regenerates the rendered points on the next
/// `PostUpdate`. The `version` counter is bumped on every mutation and
/// is what signals the sync system to do work — direct field edits via
/// `cells[i] = …` won't be picked up.
#[derive(Asset, Clone, Debug, Reflect)]
pub struct GridSplat {
    pub width: u32,
    pub height: u32,
    /// Per-cell scalar, row-major `[y * width + x]`. Default 1.0.
    pub cells: Vec<f32>,
    /// World-space spacing between adjacent cells in the local XZ plane.
    pub cell_size: Vec2,
    /// Local-space origin of cell `(0, 0)`. The grid extends in `+X` and
    /// `+Z` from here.
    pub origin: Vec3,
    /// Lift each point along local `+Y` by `value * height_scale`.
    /// 0.0 = flat grid; useful for spectral masks where the value is a
    /// gain, not a height. Default `0.0`.
    pub height_scale: f32,
    /// Per-point world size (pixels with default `SplatMaterial`).
    pub point_size: f32,
    /// Optional color ramp. When `Some`, cell value is clamped to
    /// `[0, color_value_max]`, normalized, and used as a t in [0, 1] to
    /// linearly sample the ramp. When `None`, all points are white.
    pub colormap: Option<Vec<Vec4>>,
    /// Upper end of the colormap input range. Cell values above this
    /// clamp to the last colormap entry.
    pub color_value_max: f32,
    /// Bumped on every mutation. Sync system reads this against its own
    /// last-seen value to decide whether to regenerate the splat.
    pub version: u64,
}

impl Default for GridSplat {
    fn default() -> Self {
        Self {
            width: 0,
            height: 0,
            cells: Vec::new(),
            cell_size: Vec2::ONE,
            origin: Vec3::ZERO,
            height_scale: 0.0,
            point_size: 4.0,
            colormap: None,
            color_value_max: 1.0,
            version: 0,
        }
    }
}

impl GridSplat {
    /// Allocate a `width × height` grid filled with `1.0`.
    pub fn new(width: u32, height: u32, cell_size: Vec2) -> Self {
        Self {
            width,
            height,
            cells: vec![1.0; (width as usize) * (height as usize)],
            cell_size,
            ..default()
        }
    }

    /// `(width, height)` in cells.
    pub fn dims(&self) -> (u32, u32) {
        (self.width, self.height)
    }

    /// Read one cell. Out-of-bounds returns `1.0` (the unedited default).
    pub fn get(&self, x: u32, y: u32) -> f32 {
        self.index(x, y).map(|i| self.cells[i]).unwrap_or(1.0)
    }

    /// Write one cell. Out-of-bounds is silently ignored.
    pub fn set(&mut self, x: u32, y: u32, value: f32) {
        if let Some(i) = self.index(x, y) {
            self.cells[i] = value;
            self.version = self.version.wrapping_add(1);
        }
    }

    /// Bulk write. One `version` bump for the whole batch.
    pub fn set_many<I: IntoIterator<Item = (u32, u32, f32)>>(&mut self, cells: I) {
        let mut touched = false;
        for (x, y, value) in cells {
            if let Some(i) = self.index(x, y) {
                self.cells[i] = value;
                touched = true;
            }
        }
        if touched {
            self.version = self.version.wrapping_add(1);
        }
    }

    /// Set every cell to `value`.
    pub fn fill(&mut self, value: f32) {
        for c in &mut self.cells {
            *c = value;
        }
        self.version = self.version.wrapping_add(1);
    }

    /// Iterate over `(x, y, value)` for every cell in row-major order.
    pub fn iter_cells(&self) -> impl Iterator<Item = (u32, u32, f32)> + '_ {
        let w = self.width;
        self.cells
            .iter()
            .enumerate()
            .map(move |(i, &v)| ((i as u32) % w, (i as u32) / w, v))
    }

    /// Local-space position of cell `(x, y)`'s center.
    pub fn cell_world_pos(&self, x: u32, y: u32) -> Vec3 {
        Vec3::new(
            self.origin.x + (x as f32 + 0.5) * self.cell_size.x,
            self.origin.y,
            self.origin.z + (y as f32 + 0.5) * self.cell_size.y,
        )
    }

    /// Project a local-space point onto the grid plane (`y = origin.y`),
    /// returning `Some(cell)` if it falls inside `[0..width) × [0..height)`.
    pub fn world_to_cell(&self, local_xz: Vec2) -> Option<UVec2> {
        let local = local_xz - Vec2::new(self.origin.x, self.origin.z);
        let cx = local.x / self.cell_size.x;
        let cy = local.y / self.cell_size.y;
        if cx < 0.0 || cy < 0.0 {
            return None;
        }
        let (x, y) = (cx as u32, cy as u32);
        if x >= self.width || y >= self.height {
            return None;
        }
        Some(UVec2::new(x, y))
    }

    fn index(&self, x: u32, y: u32) -> Option<usize> {
        if x >= self.width || y >= self.height {
            return None;
        }
        Some((y as usize) * (self.width as usize) + (x as usize))
    }

    fn sample_color(&self, value: f32) -> Vec4 {
        let Some(ramp) = self.colormap.as_ref() else {
            return Vec4::ONE;
        };
        if ramp.is_empty() {
            return Vec4::ONE;
        }
        let t = (value / self.color_value_max).clamp(0.0, 1.0);
        let idx = t * (ramp.len() - 1) as f32;
        let lo = idx.floor() as usize;
        let hi = (lo + 1).min(ramp.len() - 1);
        let f = idx - (lo as f32);
        ramp[lo].lerp(ramp[hi], f)
    }

    /// Build a `Splat` from the current cells. Public so the sync
    /// system (or tests) can call it; callers shouldn't normally need
    /// to invoke it directly.
    pub fn to_splat(&self) -> Splat {
        let mut points = Vec::with_capacity(self.cells.len());
        for (x, y, value) in self.iter_cells() {
            let mut pos = self.cell_world_pos(x, y);
            pos.y += value * self.height_scale;
            points.push(SplatPoint::new(pos, self.point_size, self.sample_color(value)));
        }
        Splat::with_capacity(points, self.cells.len())
    }
}

/// Component referencing a `GridSplat`. The sync system maintains a
/// `Splat3d` on the same entity that mirrors the grid's current state.
#[derive(Component, Clone, Debug, Default, Reflect)]
#[reflect(Component, Default)]
#[require(Transform, Visibility)]
pub struct GridSplat3d(pub Handle<GridSplat>);

/// Per-entity counter so the sync system rebuilds only when the grid's
/// version changes (cheap re-check vs. full point regeneration).
#[derive(Component, Default)]
pub(crate) struct LastSyncedVersion(u64);

/// Backing splat handle owned by `GridSplat3d`. Kept on the entity so we
/// reuse the same `Splat` asset across rebuilds (preserving GPU buffers
/// where capacity permits, per the existing `prepare_splat_buffers` path).
#[derive(Component)]
pub(crate) struct GridSplatBacking(pub Handle<Splat>);

/// Initialize the per-entity backing splat the first time we see a
/// `GridSplat3d`. Spawns an empty `Splat` and inserts `Splat3d` +
/// tracker components so the sync system has somewhere to write.
pub(crate) fn init_grid_backing(
    mut commands: Commands,
    mut splats: ResMut<Assets<Splat>>,
    grids: Res<Assets<GridSplat>>,
    query: Query<(Entity, &GridSplat3d), Without<GridSplatBacking>>,
) {
    for (entity, grid3d) in &query {
        let initial = grids
            .get(&grid3d.0)
            .map(GridSplat::to_splat)
            .unwrap_or_default();
        let splat_handle = splats.add(initial);
        commands.entity(entity).insert((
            Splat3d(splat_handle.clone()),
            GridSplatBacking(splat_handle),
            LastSyncedVersion::default(),
        ));
    }
}

/// Rebuild each entity's backing `Splat` whenever its `GridSplat`'s
/// version advances. Runs in `PostUpdate` so brush mutations made in
/// `Update` reflect on the next render.
pub(crate) fn sync_grid_to_splat(
    grids: Res<Assets<GridSplat>>,
    mut splats: ResMut<Assets<Splat>>,
    mut query: Query<(&GridSplat3d, &GridSplatBacking, &mut LastSyncedVersion)>,
) {
    for (grid3d, backing, mut last) in &mut query {
        let Some(grid) = grids.get(&grid3d.0) else {
            continue;
        };
        if last.0 == grid.version {
            continue;
        }
        if let Some(splat) = splats.get_mut(&backing.0) {
            *splat = grid.to_splat();
            last.0 = grid.version;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_grid_is_filled_with_ones() {
        let g = GridSplat::new(4, 3, Vec2::ONE);
        assert_eq!(g.dims(), (4, 3));
        assert_eq!(g.cells.len(), 12);
        assert!(g.cells.iter().all(|&v| v == 1.0));
    }

    #[test]
    fn set_and_get_round_trip() {
        let mut g = GridSplat::new(4, 4, Vec2::ONE);
        g.set(2, 3, 0.25);
        assert_eq!(g.get(2, 3), 0.25);
        assert_eq!(g.get(0, 0), 1.0);
    }

    #[test]
    fn set_out_of_bounds_is_a_noop() {
        let mut g = GridSplat::new(4, 4, Vec2::ONE);
        g.set(99, 99, 7.0);
        assert!(g.cells.iter().all(|&v| v == 1.0));
        assert_eq!(g.version, 0);
    }

    #[test]
    fn version_bumps_on_mutation() {
        let mut g = GridSplat::new(4, 4, Vec2::ONE);
        let v0 = g.version;
        g.set(1, 1, 0.5);
        assert_ne!(g.version, v0);
    }

    #[test]
    fn version_does_not_bump_when_no_cells_were_in_bounds() {
        let mut g = GridSplat::new(4, 4, Vec2::ONE);
        let v0 = g.version;
        g.set_many([(99, 99, 1.0), (100, 100, 1.0)]);
        assert_eq!(g.version, v0);
    }

    #[test]
    fn world_to_cell_inside_grid() {
        let g = GridSplat::new(10, 10, Vec2::splat(2.0));
        // (4.5, 6.5) in local XZ → cell 4/2 = 2, 6/2 = 3
        assert_eq!(g.world_to_cell(Vec2::new(4.5, 6.5)), Some(UVec2::new(2, 3)));
    }

    #[test]
    fn world_to_cell_outside_grid_is_none() {
        let g = GridSplat::new(10, 10, Vec2::ONE);
        assert!(g.world_to_cell(Vec2::new(-1.0, 5.0)).is_none());
        assert!(g.world_to_cell(Vec2::new(5.0, 100.0)).is_none());
    }

    #[test]
    fn to_splat_emits_one_point_per_cell() {
        let g = GridSplat::new(3, 4, Vec2::ONE);
        let splat = g.to_splat();
        assert_eq!(splat.points.len(), 12);
    }

    #[test]
    fn to_splat_lifts_by_value_when_height_scale_set() {
        let mut g = GridSplat::new(2, 1, Vec2::ONE);
        g.height_scale = 10.0;
        g.set(0, 0, 0.5);
        let splat = g.to_splat();
        // y = origin.y + value * height_scale = 0 + 0.5 * 10
        assert!((splat.points[0].position[1] - 5.0).abs() < 1e-5);
    }

    #[test]
    fn colormap_lerp_at_endpoints() {
        let mut g = GridSplat::new(1, 1, Vec2::ONE);
        g.colormap = Some(vec![Vec4::ZERO, Vec4::ONE]);
        g.color_value_max = 1.0;
        assert_eq!(g.sample_color(0.0), Vec4::ZERO);
        assert_eq!(g.sample_color(1.0), Vec4::ONE);
        assert_eq!(g.sample_color(2.0), Vec4::ONE); // clamps
    }
}
